# Generated by Django 4.2.3 on 2024-01-27 07:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='default_user', max_length=100, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('age_range', models.CharField(choices=[('1', 'Under 18'), ('2', '18-29'), ('3', '30-39'), ('4', '40-49'), ('5', '50+')], max_length=20)),
                ('last_period', models.DateField(blank=True)),
                ('exercise_purpose', models.CharField(choices=[('loseWeight', 'Lose Weight'), ('buildMuscle', 'Build Muscle'), ('stayActive', 'Stay Active')], max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('previous_cycle_lengths', models.TextField(default='[]')),
                ('previous_luteal_lengths', models.TextField(default='[]')),
                ('predicted_cycle_length', models.PositiveIntegerField(blank=True, null=True)),
                ('predicted_luteal_length', models.PositiveIntegerField(blank=True, null=True)),
                ('cycle_length', models.PositiveIntegerField(blank=True, null=True)),
                ('luteal_length', models.PositiveIntegerField(blank=True, null=True)),
                ('follicular_length', models.PositiveIntegerField(blank=True, null=True)),
                ('ovulatory_day', models.PositiveIntegerField(blank=True, null=True)),
                ('fertility_window_start', models.PositiveIntegerField(blank=True, null=True)),
                ('fertility_window_end', models.PositiveIntegerField(blank=True, null=True)),
                ('period_length', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_period_lengths', models.TextField(default='[]')),
            ],
            options={
                'verbose_name': 'Fit User',
                'verbose_name_plural': 'Fit Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CyclePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Menstrual', 'Menstrual'), ('Follicular', 'Follicular'), ('Ovulation', 'Ovulation'), ('Luteal', 'Luteal')], max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenstrualPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('intensity', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('cycle_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitflow.cyclephase')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fituser',
            name='cycle_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitflow.cyclephase'),
        ),
        migrations.AddField(
            model_name='fituser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='fituser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
