# Generated by Django 4.2.3 on 2024-03-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fituser',
            name='activation_link_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
