# Generated by Django 4.2.3 on 2024-03-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitflow', '0003_alter_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
    ]
